"""initial migration

Revision ID: 152153073858
Revises: ab07bcb2f3a6
Create Date: 2016-03-02 16:59:25.543000

"""

# revision identifiers, used by Alembic.
revision = '152153073858'
down_revision = 'ab07bcb2f3a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
