"""initial migration

Revision ID: 1917b5cf300e
Revises: 152153073858
Create Date: 2016-03-03 11:47:06.004000

"""

# revision identifiers, used by Alembic.
revision = '1917b5cf300e'
down_revision = '152153073858'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
